# wget https://darus.uni-stuttgart.de/api/access/datafile/133280 -O ./data/pdebench/ns_incom_inhom_2d_512-0.hdf5
dataset_params:
  _target_: dataloaders.cno_burger_markov.burger_markov_dataset        # dataloaders.ks.ks_markov_dataset
  filename: 1D_Burgers_Sols_Nu0.001.hdf5  
  saved_folder: "/data/user_data/rvk/data/pdebench/"
  # val_filename: KS_valid.h5
  # test_filename: KS_test.h5
  reduced_batch: 16
  reduced_resolution: 1   # CNO uses 's', so this is a dummy 1
  reduced_resolution_t: 1 # 4
  s: 64                   # Use this for CNO (Training resolution) 
  data_normalizer: true
  num_samples_max: -1

window_size: 15        # Use this for S4
original_res: 1024

multi_res:
 - 1
 - 16

train_mres: false

pde: ks

# dataset_params:
#   _target_: dataloaders.ks.ks_markov_dataset
#   filename: KS_train_2048.h5
#   saved_folder: "/data/user_data/rvk/ks/res_512/visc_0.075_L64.0_lmax8_et5.0_nte51_nt51"
#   val_filename: KS_valid.h5
#   test_filename: KS_test.h5
#   reduced_batch: 1
#   reduced_resolution: 1   # CNO uses 's', so this is a dummy 1
#   reduced_resolution_t: 4
#   s: 64                   # Use this for CNO (Training resolution) 
#   data_normalizer: true
#   num_samples_max: -1

# window_size: 15        # Use this for S4
# original_res: 512

# multi_res:
#  - 1
#  - 16

# train_mres: false

# pde: ks