# wget https://darus.uni-stuttgart.de/api/access/datafile/133280 -O ./data/pdebench/ns_incom_inhom_2d_512-0.hdf5
dataset_params:
  _target_: dataloaders.ks_resize_markov.ks_markov_dataset        # dataloaders.ks.ks_markov_dataset
  filename: KS_train_2048.h5
  saved_folder: "/data/user_data/rvk/ks/res_512/visc_0.075_L64.0_lmax8_et5.0_nte51_nt51"
  val_filename: KS_valid.h5
  test_filename: KS_test.h5
  reduced_batch: 1
  reduced_resolution: 1        # CNO uses 's', so this is a dummy 1
  reduced_resolution_t: 1 
  s: 32                        # Use this for CNO (Training resolution)  
  data_normalizer: true
  num_samples_max: -1
  normalization_type: simple

resize_to_train: false    # if we want to resize test data to train resolution during testing
train_mres: false
evaluation_type: use_resize    # use resize_function to evaluate

window_size: 15        # Use this for S4
original_res: 512
max_test_resolution: 512   # The resolution till where we want to test [32, 64, 128, 256, 512]

  

pde: ks