# wget https://darus.uni-stuttgart.de/api/access/datafile/133280 -O ./data/pdebench/ns_incom_inhom_2d_512-0.hdf5
dataset_params:
  _target_: dataloaders.active_matter_all_markov.multi_file_active_matter_markov_dataset
  file_pattern: "active_matter_*.hdf5"
  saved_folder: "/data/user_data/rvk/well/datasets/active_matter/data/train/"
  reduced_batch: 1
  reduced_resolution: 1   # CNO uses 's', so this is a dummy 1
  reduced_resolution_t: 1
  s: 64                   # Use this for CNO (Training resolution) 
  data_normalizer: true
  num_samples_max: -1

window_size: 15        # Use this for S4
original_res: 256
train_resolution: 64   # Use this for CNO

multi_res:
 - 1
 - 16

train_mres: false

pde: navier_stokes_0

