dataset_params:
  _target_: dataloaders.ns_naive_true_multires.ns_true_multires_markov_dataset       # dataloaders.ks.ks_markov_dataset
  saved_folder: "/data/user_data/rvk/ns_data"
  file_extension: ".h5"
  viscosity: "0.001"
  reduced_batch: 1
  reduced_resolution_t: 1 # 4
  data_mres_size: {256: 400, 128: 0, 64: 600}
  add_res: [32]                # Additional higher resolution for training: [32, 64] 
  add_res_samples: {32: 0}
  downsample_from_res: 64
  data_normalizer: true
  normalization_type: simple
  num_samples_max: -1

  eval_dataset_target: dataloaders.ns_naive_markov.ns_markov_dataset
  eval_filename: "ns_256_0.001.h5"  # File for evaluation (This is default: val_filename="KS_valid.h5", test_filename="KS_test.h5")
  eval_saved_folder: "/data/user_data/rvk/ns_data"  # Full path to highest res

resize_to_train: false    # if we want to resize test data to train resolution during testing
evaluation_type: naive_downsample

window_size: 15        # Use this for S4
original_res: 256
max_test_resolution: 256   # The resolution till where we want to test [32, 64, 128, 256, 512]

train_mres: true

pde: nss