# wget https://darus.uni-stuttgart.de/api/access/datafile/133280 -O ./data/pdebench/ns_incom_inhom_2d_512-0.hdf5
dataset_params:
  _target_: dataloaders.burger_resize_multires.burger_multires_markov_dataset        # dataloaders.ks.ks_markov_dataset
  filename: 1D_Burgers_Sols_Nu0.001.hdf5  
  saved_folder: "/data/user_data/rvk/data/pdebench/"
  reduced_batch: 16
  reduced_resolution: 1   # CNO uses 's', so this is a dummy 1
  reduced_resolution_t: 1 # 4
  s: 32                   # Use this for CNO (Training resolution) 
  add_res: 1024                 # Additional higher resolution for training
  num_add_res_samples: 200
  data_normalizer: true
  normalization_type: simple
  num_samples_max: -1
  eval_dataset_target: dataloaders.cno_burger_markov.burger_markov_dataset

resize_to_train: false    # cno / direct approach 
window_size: 15        # Use this for S4
original_res: 1024
max_test_resolution: 1024   # The resolution till where we want to test [32, 64, 128, 256, 512]


train_mres: true

pde: burger