dataset_params:
  _target_: dataloaders.burger_resize_true_multires.burger_true_multires_markov_dataset       # dataloaders.ks.ks_markov_dataset
  filename_pattern: 1D_Burgers_Sols_Nu*.hdf5
  saved_folder: "/data/user_data/rvk/pdebench_gen/"
  viscosity: 0.001
  reduced_batch: 1
  reduced_resolution_t: 1 # 4
  data_mres_size: {1024: 200, 512: 200, 256: 200, 128: 200}
  add_res: [32, 64]                 # Additional higher resolution for training
  add_res_samples: {64: 200, 32: 200}
  data_normalizer: true
  normalization_type: simple
  num_samples_max: -1

  eval_dataset_target: dataloaders.burger_resize_markov.burger_markov_dataset
  eval_filename: "1D_Burgers_Sols_Nu0.001.hdf5"  # File for evaluation
  eval_saved_folder: "/data/user_data/rvk/pdebench_gen/burgers_1024_0.001/"  # Full path to highest res

resize_to_train: false    # if we want to resize test data to train resolution during testing
evaluation_type: use_resize

window_size: 15        # Use this for S4
original_res: 1024
max_test_resolution: 1024   # The resolution till where we want to test [32, 64, 128, 256, 512]

train_mres: true

pde: burger