dataset_params:
  _target_: dataloaders.cno_burger_markov.burger_markov_dataset        # dataloaders.ks.ks_markov_dataset
  filename: 1D_Burgers_Sols_Nu0.1.hdf5  
  saved_folder: "/data/user_data/rvk/data/pdebench/"
  reduced_batch: 16
  reduced_resolution: 1   # CNO uses 's', so this is a dummy 1
  reduced_resolution_t: 1 # 4
  s: 1024                   # Use this for CNO (Training resolution) 
  data_normalizer: true
  num_samples_max: -1

window_size: 15        # Use this for S4
original_res: 1024

multi_res:
 - 1
 - 16

train_mres: false

pde: burger