# wget https://darus.uni-stuttgart.de/api/access/datafile/133280 -O ./data/pdebench/ns_incom_inhom_2d_512-0.hdf5
dataset_params:
  _target_: dataloaders.burger_markov.burger_markov_dataset        # dataloaders.ks.ks_markov_dataset
  filename: 1D_Burgers_Sols_Nu0.001.hdf5  
  saved_folder: "/data/user_data/rvk/data/pdebench/"
  reduced_batch: 16
  reduced_resolution_t: 1 # 4
  reduced_resolution: 32
  data_normalizer: true
  normalization_type: simple
  num_samples_max: -1

resize_to_train: false    # cno / direct approach 
window_size: 15        # Use this for S4
original_res: 1024
max_test_resolution: 1024   # The resolution till where we want to test [32, 64, 128, 256, 512]

multi_res:
 - 1
 - 16

train_mres: false

pde: ks